midtermpasigado/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('add/', views.add, name = 'add'),
    path('<int:post_id>/', views.details, name='detail'),
    path('<int:post_id>/update', views.update, name='update')
]

post/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    date_created = models.DateTimeField("Date Created", auto_now_add=True)
    date_updated = models.DateTimeField("Date updated", auto_now=True)
    content = models.TextField()
    is_active = models.BooleanField()
    #defaults to True upon creation


    def __str__(self):
        return self.title

class Comment(models.Model):
    date_created = models.DateTimeField("Date Created", auto_now=False, auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

post/forms.py
from django.forms import ModelForm 
from .models import Post, Comment

class PostModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

class CommentModelForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['id']

post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from .forms import PostModelForm, CommentModelForm

# Create your views here.

def index(request):
    context = {}
    context['posts'] = Post.objects.all().filter(is_active=True)
    return render(request, 'index.html', context)

def details(request, post_id):
    context = {}
    context['post'] = Post.objects.get(id=post_id)
    context['comment'] = CommentModelForm(initial={'post':Post.objects.get(id=post_id)})

    if request.method == 'POST':
        form = CommentModelForm(request.POST)
        
        if form.is_valid():
            form.save()
            return render(request, 'details.html', context)
    else:
        return render(request, 'details.html', context)

    return render(request, 'details.html', context)

def update(request, post_id):
    context = {}
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            return redirect('/posts/')
        else:
            context['form']  = form
            return render(request, 'update.html', context)

    else:
        context['form'] = PostModelForm(instance=post)
    return render(request, 'update.html', context)

def add(request):
    context = {}
    context['form'] = PostModelForm(initial={'is_active':True})
    
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('/posts/')
        else: 
            return render(request, 'add.html', context)
    else:
        return render(request, 'add.html', context)

post/templates/add.html
{% extends 'base.html' %}

{% block head %}
    The Add Page
{% endblock head %}

{% block body %}
    <form action="{% url 'post:add'%}" method="POST">
        {% csrf_token %}

        {% for field in  form %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <input type="submit" value="Add">
    </form>
{% endblock body %}

post/templates/base.html
{% load static %}

<html>
    <head>
        <title>
            {% block head %}
            
            {% endblock head %}
        </title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        
        {% block styles %}
        {% endblock styles %}
    </head>

    <body>
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href='{% url 'post:index' %}'>Posts</a>
        </nav>

        <div class="container">
            {% block body %}
                123456
            {% endblock body %}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

        {% block scripts %}

        {% endblock %}
    </body>
</html>

post/templates/details.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}

{% block body %}

        <div class="row mt-5 mb-3"> 
                <h1> {{ post.title }} <a href='{% url 'post:update' post.id %}'> <span class="badge badge-secondary">Edit</span> </a> </h1>
        </div>

        <div class="row"> 
                <small> Date Created: {{ post.date_created}}</small> 
        </div>
        <div class="row"> 
                <small> Last Updated: {{ post.date_updated}}</small>
        </div>
        <div class="row"> 
                <p class="text-justify mt-5 mb-5"> {{ post.content }} <p>
        </div>

        <div class="row">
                <ul class="list-group w-100">
                        {% for comment in post.comment_set.all %}
                                <a class="list-group-item list-group-item-action">
                                        <div class="d-flex w-100 justify-content-between">
                                        <small> {{ comment.date_created }} </small>
                                        </div>
                                        <p class="mb-1">{{ comment.content }}</p>
                                </a>
                                
                        {% endfor %}
                </ul>
        </div>

        <div class="row mt-5">
                <form action="{% url 'post:detail' post.id%}" method="POST">
                        {% csrf_token %}
                        <p hidden>{{comment.post}}</p>
                        {{comment.content}}

                        <button type="submit" value="Add" class="btn btn-primary mb-2">Submit</button>
                </form>
        </div>



{% endblock body %}

post/templates/index.html
{% extends "base.html" %} 

{% block head %}
    this is the title page
{% endblock head %}

{% block body %}
    <div class="row mt-5 mb-5">
        <h2 class="ml-3"> All Posts <a href='{% url 'post:add' %}'> <span class="btn btn-outline-primary ml-3">Add New Post</span> </a> </h2>
    </div>
    <div class="list-group">
        {% for post in posts %}
            <a href="{% url 'post:detail' post.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ post.title }}</h5>
                    <small> {{ post.date_created }} </small>
                </div>

                <p class="mb-1"> {{ post.content }} </p>
                <small>Last Updated: {{ post.date_updated }} </small>
            </a>

        {% endfor %}
    </div>
{% endblock body %}

post/templates/update.html
{% extends 'base.html' %}

{% block head %}
    The Update Page
{% endblock head %}

{% block body %}
    <form action="{% url 'post:update' form.instance.id %}" method="POST">
        {% csrf_token %}

        {% for field in  form %}
            {{ field.label }}
            {{ field }}
        {% endfor %}

        <input type="submit" value="Update">
    </form>
{% endblock body %}